#!/usr/bin/env bash

mkdir -p traces
tid=`cat TID`
tid=$((tid+1))

echo $tid > TID

./replace "$@" > /dev/null
../../../scripts/instcov-view.sh -t dump.instcov replace.i.c.dbginfo -o traces/replace.${tid}.pt
