#!/usr/bin/env bash

mkdir -p traces
tid=`cat TID`
tid=$((tid+1))

echo $tid > TID

./print_tokens "$@" > /dev/null
../../../scripts/instcov-view.sh -t dump.instcov print_tokens.i.c.dbginfo -o traces/print_tokens.${tid}.pt
