#!/usr/bin/env bash

mkdir -p traces
tid=`cat TID`
tid=$((tid+1))

echo $tid > TID

./schedule2 "$@" > /dev/null
../../../scripts/instcov_view.py -t dump.instcov schedule2.i.c.dbginfo -o traces/schedule2.${tid}.pt
