#!/usr/bin/env bash

mkdir -p traces_sc
tid=`cat TID`
tid=$((tid+1))

echo $tid > TID

./testsc "$@" > /dev/null
../../scripts/instcov-view.sh -t dump.instcov testsc.i.cpp.dbginfo -o traces_sc/test.${tid}.pt
